//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ClassPaymentGateway.StatusResult {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    [System.Xml.Serialization.XmlRootAttribute("statusResult", Namespace="http://gateway.bankart.si/Schema/V2/StatusResult", IsNullable=false)]
    public partial class statusResultType {
        
        private bool operationSuccessField;
        
        private transactionStatusType transactionStatusField;
        
        private bool transactionStatusFieldSpecified;
        
        private string transactionUuidField;
        
        private string merchantTransactionIdField;
        
        private string purchaseIdField;
        
        private transactionMethodType transactionTypeField;
        
        private bool transactionTypeFieldSpecified;
        
        private string paymentMethodField;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string currencyField;
        
        private string scheduleIdField;
        
        private scheduleStatusType scheduleStatusField;
        
        private bool scheduleStatusFieldSpecified;
        
        private errorType[] errorsField;
        
        private chargebackDataType chargebackDataField;
        
        private chargebackReversalDataType chargebackReversalDataField;
        
        private extraDataType[] extraDataField;
        
        private string merchantMetaDataField;
        
        private returnDataType returnDataField;
        
        private customerDataType customerDataField;
        
        /// <remarks/>
        public bool operationSuccess {
            get {
                return this.operationSuccessField;
            }
            set {
                this.operationSuccessField = value;
            }
        }
        
        /// <remarks/>
        public transactionStatusType transactionStatus {
            get {
                return this.transactionStatusField;
            }
            set {
                this.transactionStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionStatusSpecified {
            get {
                return this.transactionStatusFieldSpecified;
            }
            set {
                this.transactionStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string transactionUuid {
            get {
                return this.transactionUuidField;
            }
            set {
                this.transactionUuidField = value;
            }
        }
        
        /// <remarks/>
        public string merchantTransactionId {
            get {
                return this.merchantTransactionIdField;
            }
            set {
                this.merchantTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string purchaseId {
            get {
                return this.purchaseIdField;
            }
            set {
                this.purchaseIdField = value;
            }
        }
        
        /// <remarks/>
        public transactionMethodType transactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionTypeSpecified {
            get {
                return this.transactionTypeFieldSpecified;
            }
            set {
                this.transactionTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string paymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string scheduleId {
            get {
                return this.scheduleIdField;
            }
            set {
                this.scheduleIdField = value;
            }
        }
        
        /// <remarks/>
        public scheduleStatusType scheduleStatus {
            get {
                return this.scheduleStatusField;
            }
            set {
                this.scheduleStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scheduleStatusSpecified {
            get {
                return this.scheduleStatusFieldSpecified;
            }
            set {
                this.scheduleStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("error", IsNullable=false)]
        public errorType[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        public chargebackDataType chargebackData {
            get {
                return this.chargebackDataField;
            }
            set {
                this.chargebackDataField = value;
            }
        }
        
        /// <remarks/>
        public chargebackReversalDataType chargebackReversalData {
            get {
                return this.chargebackReversalDataField;
            }
            set {
                this.chargebackReversalDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extraData")]
        public extraDataType[] extraData {
            get {
                return this.extraDataField;
            }
            set {
                this.extraDataField = value;
            }
        }
        
        /// <remarks/>
        public string merchantMetaData {
            get {
                return this.merchantMetaDataField;
            }
            set {
                this.merchantMetaDataField = value;
            }
        }
        
        /// <remarks/>
        public returnDataType returnData {
            get {
                return this.returnDataField;
            }
            set {
                this.returnDataField = value;
            }
        }
        
        /// <remarks/>
        public customerDataType customerData {
            get {
                return this.customerDataField;
            }
            set {
                this.customerDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public enum transactionStatusType {
        
        /// <remarks/>
        SUCCESS,
        
        /// <remarks/>
        PENDING,
        
        /// <remarks/>
        REDIRECT,
        
        /// <remarks/>
        CANCELLED,
        
        /// <remarks/>
        ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public enum transactionMethodType {
        
        /// <remarks/>
        DEBIT,
        
        /// <remarks/>
        CAPTURE,
        
        /// <remarks/>
        DEREGISTER,
        
        /// <remarks/>
        PREAUTHORIZE,
        
        /// <remarks/>
        REFUND,
        
        /// <remarks/>
        REGISTER,
        
        /// <remarks/>
        VOID,
        
        /// <remarks/>
        CHARGEBACK,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CHARGEBACK-REVERSAL")]
        CHARGEBACKREVERSAL,
        
        /// <remarks/>
        PAYOUT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public enum scheduleStatusType {
        
        /// <remarks/>
        ACTIVE,
        
        /// <remarks/>
        PAUSED,
        
        /// <remarks/>
        CANCELLED,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CREATE-PENDING")]
        CREATEPENDING,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public partial class errorType {
        
        private string messageField;
        
        private string codeField;
        
        private string adapterMessageField;
        
        private string adapterCodeField;
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string adapterMessage {
            get {
                return this.adapterMessageField;
            }
            set {
                this.adapterMessageField = value;
            }
        }
        
        /// <remarks/>
        public string adapterCode {
            get {
                return this.adapterCodeField;
            }
            set {
                this.adapterCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public partial class customerDataType {
        
        private string identificationField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private genderType genderField;
        
        private bool genderFieldSpecified;
        
        private string billingAddress1Field;
        
        private string billingAddress2Field;
        
        private string billingCityField;
        
        private string billingPostcodeField;
        
        private string billingStateField;
        
        private string billingCountryField;
        
        private string billingPhoneField;
        
        private string shippingFirstNameField;
        
        private string shippingLastNameField;
        
        private string shippingCompanyField;
        
        private string shippingAddress1Field;
        
        private string shippingAddress2Field;
        
        private string shippingCityField;
        
        private string shippingPostcodeField;
        
        private string shippingStateField;
        
        private string shippingCountryField;
        
        private string shippingPhoneField;
        
        private string companyField;
        
        private string emailField;
        
        private bool emailVerifiedField;
        
        private bool emailVerifiedFieldSpecified;
        
        private string ipAddressField;
        
        private string nationalIdField;
        
        /// <remarks/>
        public string identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public genderType gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool genderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string billingAddress1 {
            get {
                return this.billingAddress1Field;
            }
            set {
                this.billingAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string billingAddress2 {
            get {
                return this.billingAddress2Field;
            }
            set {
                this.billingAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string billingCity {
            get {
                return this.billingCityField;
            }
            set {
                this.billingCityField = value;
            }
        }
        
        /// <remarks/>
        public string billingPostcode {
            get {
                return this.billingPostcodeField;
            }
            set {
                this.billingPostcodeField = value;
            }
        }
        
        /// <remarks/>
        public string billingState {
            get {
                return this.billingStateField;
            }
            set {
                this.billingStateField = value;
            }
        }
        
        /// <remarks/>
        public string billingCountry {
            get {
                return this.billingCountryField;
            }
            set {
                this.billingCountryField = value;
            }
        }
        
        /// <remarks/>
        public string billingPhone {
            get {
                return this.billingPhoneField;
            }
            set {
                this.billingPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string shippingFirstName {
            get {
                return this.shippingFirstNameField;
            }
            set {
                this.shippingFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string shippingLastName {
            get {
                return this.shippingLastNameField;
            }
            set {
                this.shippingLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string shippingCompany {
            get {
                return this.shippingCompanyField;
            }
            set {
                this.shippingCompanyField = value;
            }
        }
        
        /// <remarks/>
        public string shippingAddress1 {
            get {
                return this.shippingAddress1Field;
            }
            set {
                this.shippingAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string shippingAddress2 {
            get {
                return this.shippingAddress2Field;
            }
            set {
                this.shippingAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string shippingCity {
            get {
                return this.shippingCityField;
            }
            set {
                this.shippingCityField = value;
            }
        }
        
        /// <remarks/>
        public string shippingPostcode {
            get {
                return this.shippingPostcodeField;
            }
            set {
                this.shippingPostcodeField = value;
            }
        }
        
        /// <remarks/>
        public string shippingState {
            get {
                return this.shippingStateField;
            }
            set {
                this.shippingStateField = value;
            }
        }
        
        /// <remarks/>
        public string shippingCountry {
            get {
                return this.shippingCountryField;
            }
            set {
                this.shippingCountryField = value;
            }
        }
        
        /// <remarks/>
        public string shippingPhone {
            get {
                return this.shippingPhoneField;
            }
            set {
                this.shippingPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public bool emailVerified {
            get {
                return this.emailVerifiedField;
            }
            set {
                this.emailVerifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emailVerifiedSpecified {
            get {
                return this.emailVerifiedFieldSpecified;
            }
            set {
                this.emailVerifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        public string nationalId {
            get {
                return this.nationalIdField;
            }
            set {
                this.nationalIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public enum genderType {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public partial class ibanDataType {
        
        private string accountOwnerField;
        
        private string ibanField;
        
        private string bicField;
        
        private string bankNameField;
        
        private string countryField;
        
        /// <remarks/>
        public string accountOwner {
            get {
                return this.accountOwnerField;
            }
            set {
                this.accountOwnerField = value;
            }
        }
        
        /// <remarks/>
        public string iban {
            get {
                return this.ibanField;
            }
            set {
                this.ibanField = value;
            }
        }
        
        /// <remarks/>
        public string bic {
            get {
                return this.bicField;
            }
            set {
                this.bicField = value;
            }
        }
        
        /// <remarks/>
        public string bankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public partial class phoneDataType {
        
        private string phoneNumberField;
        
        private string countryField;
        
        private string operatorField;
        
        /// <remarks/>
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string @operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public partial class creditcardDataType {
        
        private string typeField;
        
        private string countryField;
        
        private string cardHolderField;
        
        private string expiryMonthField;
        
        private string expiryYearField;
        
        private string firstSixDigitsField;
        
        private string lastFourDigitsField;
        
        private string fingerprintField;
        
        private string binBrandField;
        
        private string binBankField;
        
        private string binTypeField;
        
        private string binLevelField;
        
        private string binCountryField;
        
        private threeDSecureType threeDSecureField;
        
        private bool threeDSecureFieldSpecified;
        
        private string eciField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string cardHolder {
            get {
                return this.cardHolderField;
            }
            set {
                this.cardHolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string expiryMonth {
            get {
                return this.expiryMonthField;
            }
            set {
                this.expiryMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string expiryYear {
            get {
                return this.expiryYearField;
            }
            set {
                this.expiryYearField = value;
            }
        }
        
        /// <remarks/>
        public string firstSixDigits {
            get {
                return this.firstSixDigitsField;
            }
            set {
                this.firstSixDigitsField = value;
            }
        }
        
        /// <remarks/>
        public string lastFourDigits {
            get {
                return this.lastFourDigitsField;
            }
            set {
                this.lastFourDigitsField = value;
            }
        }
        
        /// <remarks/>
        public string fingerprint {
            get {
                return this.fingerprintField;
            }
            set {
                this.fingerprintField = value;
            }
        }
        
        /// <remarks/>
        public string binBrand {
            get {
                return this.binBrandField;
            }
            set {
                this.binBrandField = value;
            }
        }
        
        /// <remarks/>
        public string binBank {
            get {
                return this.binBankField;
            }
            set {
                this.binBankField = value;
            }
        }
        
        /// <remarks/>
        public string binType {
            get {
                return this.binTypeField;
            }
            set {
                this.binTypeField = value;
            }
        }
        
        /// <remarks/>
        public string binLevel {
            get {
                return this.binLevelField;
            }
            set {
                this.binLevelField = value;
            }
        }
        
        /// <remarks/>
        public string binCountry {
            get {
                return this.binCountryField;
            }
            set {
                this.binCountryField = value;
            }
        }
        
        /// <remarks/>
        public threeDSecureType threeDSecure {
            get {
                return this.threeDSecureField;
            }
            set {
                this.threeDSecureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool threeDSecureSpecified {
            get {
                return this.threeDSecureFieldSpecified;
            }
            set {
                this.threeDSecureFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string eci {
            get {
                return this.eciField;
            }
            set {
                this.eciField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public enum threeDSecureType {
        
        /// <remarks/>
        OFF,
        
        /// <remarks/>
        OPTIONAL,
        
        /// <remarks/>
        MANDATORY,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public partial class returnDataType {
        
        private object itemField;
        
        private returnDataTypeEnum typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creditcardData", typeof(creditcardDataType))]
        [System.Xml.Serialization.XmlElementAttribute("ibanData", typeof(ibanDataType))]
        [System.Xml.Serialization.XmlElementAttribute("phoneData", typeof(phoneDataType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public returnDataTypeEnum type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public enum returnDataTypeEnum {
        
        /// <remarks/>
        creditcardData,
        
        /// <remarks/>
        phoneData,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public partial class extraDataType {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public partial class chargebackReversalDataType {
        
        private string originalReferenceIdField;
        
        private string originalTransactionIdField;
        
        private string chargebackReferenceIdField;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string currencyField;
        
        private string reasonField;
        
        private System.DateTime reversalDateTimeField;
        
        private bool reversalDateTimeFieldSpecified;
        
        /// <remarks/>
        public string originalReferenceId {
            get {
                return this.originalReferenceIdField;
            }
            set {
                this.originalReferenceIdField = value;
            }
        }
        
        /// <remarks/>
        public string originalTransactionId {
            get {
                return this.originalTransactionIdField;
            }
            set {
                this.originalTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string chargebackReferenceId {
            get {
                return this.chargebackReferenceIdField;
            }
            set {
                this.chargebackReferenceIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime reversalDateTime {
            get {
                return this.reversalDateTimeField;
            }
            set {
                this.reversalDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reversalDateTimeSpecified {
            get {
                return this.reversalDateTimeFieldSpecified;
            }
            set {
                this.reversalDateTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/StatusResult")]
    public partial class chargebackDataType {
        
        private string originalReferenceIdField;
        
        private string originalTransactionIdField;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string currencyField;
        
        private string reasonField;
        
        private System.DateTime chargebackDateTimeField;
        
        private bool chargebackDateTimeFieldSpecified;
        
        /// <remarks/>
        public string originalReferenceId {
            get {
                return this.originalReferenceIdField;
            }
            set {
                this.originalReferenceIdField = value;
            }
        }
        
        /// <remarks/>
        public string originalTransactionId {
            get {
                return this.originalTransactionIdField;
            }
            set {
                this.originalTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime chargebackDateTime {
            get {
                return this.chargebackDateTimeField;
            }
            set {
                this.chargebackDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool chargebackDateTimeSpecified {
            get {
                return this.chargebackDateTimeFieldSpecified;
            }
            set {
                this.chargebackDateTimeFieldSpecified = value;
            }
        }
    }
}
