//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace ClassPaymentGateway.Transaction{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    [System.Xml.Serialization.XmlRootAttribute("transaction", Namespace="http://gateway.bankart.si/Schema/V2/Transaction", IsNullable=false)]
    public partial class transactionType {
        
        private string usernameField;
        
        private string passwordField;
        
        private string languageField;
        
        private bool testModeField;
        
        private bool testModeFieldSpecified;
        
        private baseTransactionType itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public bool testMode {
            get {
                return this.testModeField;
            }
            set {
                this.testModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool testModeSpecified {
            get {
                return this.testModeFieldSpecified;
            }
            set {
                this.testModeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("capture", typeof(captureType))]
        [System.Xml.Serialization.XmlElementAttribute("completeDebit", typeof(debitType))]
        [System.Xml.Serialization.XmlElementAttribute("completePreauthorize", typeof(preauthorizeType))]
        [System.Xml.Serialization.XmlElementAttribute("completeRegister", typeof(registerType))]
        [System.Xml.Serialization.XmlElementAttribute("debit", typeof(debitType))]
        [System.Xml.Serialization.XmlElementAttribute("deregister", typeof(deregisterType))]
        [System.Xml.Serialization.XmlElementAttribute("payout", typeof(payoutType))]
        [System.Xml.Serialization.XmlElementAttribute("preauthorize", typeof(preauthorizeType))]
        [System.Xml.Serialization.XmlElementAttribute("refund", typeof(refundType))]
        [System.Xml.Serialization.XmlElementAttribute("register", typeof(registerType))]
        [System.Xml.Serialization.XmlElementAttribute("void", typeof(voidType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public baseTransactionType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class captureType : baseTransactionWithReferenceType {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string currencyField;
        
        private itemType[] itemsField;
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public itemType[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class itemType {
        
        private string identificationField;
        
        private string nameField;
        
        private string descriptionField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        private string currencyField;
        
        private extraDataType[] extraDataField;
        
        /// <remarks/>
        public string identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified {
            get {
                return this.priceFieldSpecified;
            }
            set {
                this.priceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extraData")]
        public extraDataType[] extraData {
            get {
                return this.extraDataField;
            }
            set {
                this.extraDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class extraDataType {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class addToCustomerProfileType {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private bool markAsPreferredField;
        
        private bool markAsPreferredFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customerIdentification", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("profileGuid", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public bool markAsPreferred {
            get {
                return this.markAsPreferredField;
            }
            set {
                this.markAsPreferredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool markAsPreferredSpecified {
            get {
                return this.markAsPreferredFieldSpecified;
            }
            set {
                this.markAsPreferredFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        customerIdentification,
        
        /// <remarks/>
        profileGuid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class scheduleType {
        
        private decimal amountField;
        
        private string currencyField;
        
        private uint periodLengthField;
        
        private periodUnitType periodUnitField;
        
        private string startDateTimeField;
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public uint periodLength {
            get {
                return this.periodLengthField;
            }
            set {
                this.periodLengthField = value;
            }
        }
        
        /// <remarks/>
        public periodUnitType periodUnit {
            get {
                return this.periodUnitField;
            }
            set {
                this.periodUnitField = value;
            }
        }
        
        /// <remarks/>
        public string startDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public enum periodUnitType {
        
        /// <remarks/>
        DAY,
        
        /// <remarks/>
        WEEK,
        
        /// <remarks/>
        MONTH,
        
        /// <remarks/>
        YEAR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class requestType {
        
        private extraDataType[] getParamField;
        
        private extraDataType[] postParamField;
        
        private extraDataType[] requestHeaderField;
        
        private string requestBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("getParam")]
        public extraDataType[] getParam {
            get {
                return this.getParamField;
            }
            set {
                this.getParamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("postParam")]
        public extraDataType[] postParam {
            get {
                return this.postParamField;
            }
            set {
                this.postParamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requestHeader")]
        public extraDataType[] requestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                this.requestHeaderField = value;
            }
        }
        
        /// <remarks/>
        public string requestBody {
            get {
                return this.requestBodyField;
            }
            set {
                this.requestBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ibanCustomerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(creditCardCustomerType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class customerType {
        
        private string identificationField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private genderType genderField;
        
        private bool genderFieldSpecified;
        
        private string billingAddress1Field;
        
        private string billingAddress2Field;
        
        private string billingCityField;
        
        private string billingPostcodeField;
        
        private string billingStateField;
        
        private string billingCountryField;
        
        private string billingPhoneField;
        
        private string shippingFirstNameField;
        
        private string shippingLastNameField;
        
        private string shippingCompanyField;
        
        private string shippingAddress1Field;
        
        private string shippingAddress2Field;
        
        private string shippingCityField;
        
        private string shippingPostcodeField;
        
        private string shippingStateField;
        
        private string shippingCountryField;
        
        private string shippingPhoneField;
        
        private string companyField;
        
        private string emailField;
        
        private bool emailVerifiedField;
        
        private bool emailVerifiedFieldSpecified;
        
        private string ipAddressField;
        
        private string nationalIdField;
        
        private extraDataType[] extraDataField;
        
        /// <remarks/>
        public string identification {
            get {
                return this.identificationField;
            }
            set {
                this.identificationField = value;
            }
        }
        
        /// <remarks/>
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public genderType gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool genderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string billingAddress1 {
            get {
                return this.billingAddress1Field;
            }
            set {
                this.billingAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string billingAddress2 {
            get {
                return this.billingAddress2Field;
            }
            set {
                this.billingAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string billingCity {
            get {
                return this.billingCityField;
            }
            set {
                this.billingCityField = value;
            }
        }
        
        /// <remarks/>
        public string billingPostcode {
            get {
                return this.billingPostcodeField;
            }
            set {
                this.billingPostcodeField = value;
            }
        }
        
        /// <remarks/>
        public string billingState {
            get {
                return this.billingStateField;
            }
            set {
                this.billingStateField = value;
            }
        }
        
        /// <remarks/>
        public string billingCountry {
            get {
                return this.billingCountryField;
            }
            set {
                this.billingCountryField = value;
            }
        }
        
        /// <remarks/>
        public string billingPhone {
            get {
                return this.billingPhoneField;
            }
            set {
                this.billingPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string shippingFirstName {
            get {
                return this.shippingFirstNameField;
            }
            set {
                this.shippingFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string shippingLastName {
            get {
                return this.shippingLastNameField;
            }
            set {
                this.shippingLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string shippingCompany {
            get {
                return this.shippingCompanyField;
            }
            set {
                this.shippingCompanyField = value;
            }
        }
        
        /// <remarks/>
        public string shippingAddress1 {
            get {
                return this.shippingAddress1Field;
            }
            set {
                this.shippingAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string shippingAddress2 {
            get {
                return this.shippingAddress2Field;
            }
            set {
                this.shippingAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string shippingCity {
            get {
                return this.shippingCityField;
            }
            set {
                this.shippingCityField = value;
            }
        }
        
        /// <remarks/>
        public string shippingPostcode {
            get {
                return this.shippingPostcodeField;
            }
            set {
                this.shippingPostcodeField = value;
            }
        }
        
        /// <remarks/>
        public string shippingState {
            get {
                return this.shippingStateField;
            }
            set {
                this.shippingStateField = value;
            }
        }
        
        /// <remarks/>
        public string shippingCountry {
            get {
                return this.shippingCountryField;
            }
            set {
                this.shippingCountryField = value;
            }
        }
        
        /// <remarks/>
        public string shippingPhone {
            get {
                return this.shippingPhoneField;
            }
            set {
                this.shippingPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public bool emailVerified {
            get {
                return this.emailVerifiedField;
            }
            set {
                this.emailVerifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool emailVerifiedSpecified {
            get {
                return this.emailVerifiedFieldSpecified;
            }
            set {
                this.emailVerifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ipAddress {
            get {
                return this.ipAddressField;
            }
            set {
                this.ipAddressField = value;
            }
        }
        
        /// <remarks/>
        public string nationalId {
            get {
                return this.nationalIdField;
            }
            set {
                this.nationalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extraData")]
        public extraDataType[] extraData {
            get {
                return this.extraDataField;
            }
            set {
                this.extraDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public enum genderType {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class ibanCustomerType : customerType {
        
        private string ibanField;
        
        private string bicField;
        
        private string mandateIdField;
        
        private System.DateTime mandateDateField;
        
        private bool mandateDateFieldSpecified;
        
        /// <remarks/>
        public string iban {
            get {
                return this.ibanField;
            }
            set {
                this.ibanField = value;
            }
        }
        
        /// <remarks/>
        public string bic {
            get {
                return this.bicField;
            }
            set {
                this.bicField = value;
            }
        }
        
        /// <remarks/>
        public string mandateId {
            get {
                return this.mandateIdField;
            }
            set {
                this.mandateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime mandateDate {
            get {
                return this.mandateDateField;
            }
            set {
                this.mandateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mandateDateSpecified {
            get {
                return this.mandateDateFieldSpecified;
            }
            set {
                this.mandateDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class creditCardCustomerType : customerType {
        
        private string numberField;
        
        private string expiryMonthField;
        
        private string expiryYearField;
        
        private string startMonthField;
        
        private string startYearField;
        
        private string cvvField;
        
        private string issueNumberField;
        
        private string typeField;
        
        /// <remarks/>
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public string expiryMonth {
            get {
                return this.expiryMonthField;
            }
            set {
                this.expiryMonthField = value;
            }
        }
        
        /// <remarks/>
        public string expiryYear {
            get {
                return this.expiryYearField;
            }
            set {
                this.expiryYearField = value;
            }
        }
        
        /// <remarks/>
        public string startMonth {
            get {
                return this.startMonthField;
            }
            set {
                this.startMonthField = value;
            }
        }
        
        /// <remarks/>
        public string startYear {
            get {
                return this.startYearField;
            }
            set {
                this.startYearField = value;
            }
        }
        
        /// <remarks/>
        public string cvv {
            get {
                return this.cvvField;
            }
            set {
                this.cvvField = value;
            }
        }
        
        /// <remarks/>
        public string issueNumber {
            get {
                return this.issueNumberField;
            }
            set {
                this.issueNumberField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(registerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(baseTransactionWithReferenceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(payoutType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(deregisterType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refundType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(voidType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(captureType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(preauthorizeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(debitType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class baseTransactionType {
        
        private string transactionTokenField;
        
        private string transactionIdField;
        
        private string additionalId1Field;
        
        private string additionalId2Field;
        
        private customerType itemField;
        
        private extraDataType[] extraDataField;
        
        private string merchantMetaDataField;
        
        private requestType requestField;
        
        /// <remarks/>
        public string transactionToken {
            get {
                return this.transactionTokenField;
            }
            set {
                this.transactionTokenField = value;
            }
        }
        
        /// <remarks/>
        public string transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string additionalId1 {
            get {
                return this.additionalId1Field;
            }
            set {
                this.additionalId1Field = value;
            }
        }
        
        /// <remarks/>
        public string additionalId2 {
            get {
                return this.additionalId2Field;
            }
            set {
                this.additionalId2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creditCardCustomer", typeof(creditCardCustomerType))]
        [System.Xml.Serialization.XmlElementAttribute("customer", typeof(customerType))]
        [System.Xml.Serialization.XmlElementAttribute("ibanCustomer", typeof(ibanCustomerType))]
        public customerType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("extraData")]
        public extraDataType[] extraData {
            get {
                return this.extraDataField;
            }
            set {
                this.extraDataField = value;
            }
        }
        
        /// <remarks/>
        public string merchantMetaData {
            get {
                return this.merchantMetaDataField;
            }
            set {
                this.merchantMetaDataField = value;
            }
        }
        
        /// <remarks/>
        public requestType request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class registerType : baseTransactionType {
        
        private string descriptionField;
        
        private string successUrlField;
        
        private string cancelUrlField;
        
        private string errorUrlField;
        
        private string callbackUrlField;
        
        private scheduleType startScheduleField;
        
        private addToCustomerProfileType addToCustomerProfileField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string successUrl {
            get {
                return this.successUrlField;
            }
            set {
                this.successUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string cancelUrl {
            get {
                return this.cancelUrlField;
            }
            set {
                this.cancelUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string errorUrl {
            get {
                return this.errorUrlField;
            }
            set {
                this.errorUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string callbackUrl {
            get {
                return this.callbackUrlField;
            }
            set {
                this.callbackUrlField = value;
            }
        }
        
        /// <remarks/>
        public scheduleType startSchedule {
            get {
                return this.startScheduleField;
            }
            set {
                this.startScheduleField = value;
            }
        }
        
        /// <remarks/>
        public addToCustomerProfileType addToCustomerProfile {
            get {
                return this.addToCustomerProfileField;
            }
            set {
                this.addToCustomerProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(payoutType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(deregisterType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(refundType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(voidType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(captureType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(preauthorizeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(debitType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class baseTransactionWithReferenceType : baseTransactionType {
        
        private string referenceTransactionIdField;
        
        private string referenceCustomerIdField;
        
        private string referenceId2Field;
        
        private string referenceId3Field;
        
        private string referenceId4Field;
        
        /// <remarks/>
        public string referenceTransactionId {
            get {
                return this.referenceTransactionIdField;
            }
            set {
                this.referenceTransactionIdField = value;
            }
        }
        
        /// <remarks/>
        public string referenceCustomerId {
            get {
                return this.referenceCustomerIdField;
            }
            set {
                this.referenceCustomerIdField = value;
            }
        }
        
        /// <remarks/>
        public string referenceId2 {
            get {
                return this.referenceId2Field;
            }
            set {
                this.referenceId2Field = value;
            }
        }
        
        /// <remarks/>
        public string referenceId3 {
            get {
                return this.referenceId3Field;
            }
            set {
                this.referenceId3Field = value;
            }
        }
        
        /// <remarks/>
        public string referenceId4 {
            get {
                return this.referenceId4Field;
            }
            set {
                this.referenceId4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class payoutType : baseTransactionWithReferenceType {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string currencyField;
        
        private string descriptionField;
        
        private string callbackUrlField;
        
        private itemType[] itemsField;
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string callbackUrl {
            get {
                return this.callbackUrlField;
            }
            set {
                this.callbackUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public itemType[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class deregisterType : baseTransactionWithReferenceType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class refundType : baseTransactionWithReferenceType {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string currencyField;
        
        private string descriptionField;
        
        private string callbackUrlField;
        
        private itemType[] itemsField;
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string callbackUrl {
            get {
                return this.callbackUrlField;
            }
            set {
                this.callbackUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public itemType[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class voidType : baseTransactionWithReferenceType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class preauthorizeType : baseTransactionWithReferenceType {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string currencyField;
        
        private string descriptionField;
        
        private string successUrlField;
        
        private string cancelUrlField;
        
        private string errorUrlField;
        
        private string callbackUrlField;
        
        private itemType[] itemsField;
        
        private bool withRegisterField;
        
        private bool withRegisterFieldSpecified;
        
        private transactionIndicatorType transactionIndicatorField;
        
        private bool transactionIndicatorFieldSpecified;
        
        private scheduleType startScheduleField;
        
        private addToCustomerProfileType addToCustomerProfileField;
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string successUrl {
            get {
                return this.successUrlField;
            }
            set {
                this.successUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string cancelUrl {
            get {
                return this.cancelUrlField;
            }
            set {
                this.cancelUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string errorUrl {
            get {
                return this.errorUrlField;
            }
            set {
                this.errorUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string callbackUrl {
            get {
                return this.callbackUrlField;
            }
            set {
                this.callbackUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public itemType[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public bool withRegister {
            get {
                return this.withRegisterField;
            }
            set {
                this.withRegisterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool withRegisterSpecified {
            get {
                return this.withRegisterFieldSpecified;
            }
            set {
                this.withRegisterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public transactionIndicatorType transactionIndicator {
            get {
                return this.transactionIndicatorField;
            }
            set {
                this.transactionIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionIndicatorSpecified {
            get {
                return this.transactionIndicatorFieldSpecified;
            }
            set {
                this.transactionIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public scheduleType startSchedule {
            get {
                return this.startScheduleField;
            }
            set {
                this.startScheduleField = value;
            }
        }
        
        /// <remarks/>
        public addToCustomerProfileType addToCustomerProfile {
            get {
                return this.addToCustomerProfileField;
            }
            set {
                this.addToCustomerProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public enum transactionIndicatorType {
        
        /// <remarks/>
        SINGLE,
        
        /// <remarks/>
        INITIAL,
        
        /// <remarks/>
        RECURRING,
        
        /// <remarks/>
        CARDONFILE,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("CARDONFILE-MERCHANT-INITIATED")]
        CARDONFILEMERCHANTINITIATED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction")]
    public partial class debitType : baseTransactionWithReferenceType {
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string currencyField;
        
        private string descriptionField;
        
        private string successUrlField;
        
        private string cancelUrlField;
        
        private string errorUrlField;
        
        private string callbackUrlField;
        
        private itemType[] itemsField;
        
        private bool withRegisterField;
        
        private bool withRegisterFieldSpecified;
        
        private transactionIndicatorType transactionIndicatorField;
        
        private bool transactionIndicatorFieldSpecified;
        
        private scheduleType startScheduleField;
        
        private addToCustomerProfileType addToCustomerProfileField;
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string successUrl {
            get {
                return this.successUrlField;
            }
            set {
                this.successUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string cancelUrl {
            get {
                return this.cancelUrlField;
            }
            set {
                this.cancelUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string errorUrl {
            get {
                return this.errorUrlField;
            }
            set {
                this.errorUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string callbackUrl {
            get {
                return this.callbackUrlField;
            }
            set {
                this.callbackUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public itemType[] items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        public bool withRegister {
            get {
                return this.withRegisterField;
            }
            set {
                this.withRegisterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool withRegisterSpecified {
            get {
                return this.withRegisterFieldSpecified;
            }
            set {
                this.withRegisterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public transactionIndicatorType transactionIndicator {
            get {
                return this.transactionIndicatorField;
            }
            set {
                this.transactionIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionIndicatorSpecified {
            get {
                return this.transactionIndicatorFieldSpecified;
            }
            set {
                this.transactionIndicatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public scheduleType startSchedule {
            get {
                return this.startScheduleField;
            }
            set {
                this.startScheduleField = value;
            }
        }
        
        /// <remarks/>
        public addToCustomerProfileType addToCustomerProfile {
            get {
                return this.addToCustomerProfileField;
            }
            set {
                this.addToCustomerProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://gateway.bankart.si/Schema/V2/Transaction", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        capture,
        
        /// <remarks/>
        completeDebit,
        
        /// <remarks/>
        completePreauthorize,
        
        /// <remarks/>
        completeRegister,
        
        /// <remarks/>
        debit,
        
        /// <remarks/>
        deregister,
        
        /// <remarks/>
        payout,
        
        /// <remarks/>
        preauthorize,
        
        /// <remarks/>
        refund,
        
        /// <remarks/>
        register,
        
        /// <remarks/>
        @void,
    }
}
